//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class videojuegosDBEntities : DbContext
    {
        public videojuegosDBEntities()
            : base("name=videojuegosDBEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<copias> copias { get; set; }
        public virtual DbSet<existencias> existencias { get; set; }
        public virtual DbSet<lineasventa> lineasventa { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
        public virtual DbSet<desarrolladores> desarrolladores { get; set; }
        public virtual DbSet<distribudores> distribudores { get; set; }
        public virtual DbSet<etiquetas> etiquetas { get; set; }
        public virtual DbSet<generos> generos { get; set; }
        public virtual DbSet<juego_etiqueta> juego_etiqueta { get; set; }
        public virtual DbSet<juegos> juegos { get; set; }
    
        public virtual ObjectResult<SP_ValidarUsuario_Result> SP_ValidarUsuario(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ValidarUsuario_Result>("SP_ValidarUsuario", emailParameter, passwordParameter);
        }
    }
}
